{% set name = "urbansim_defaults" %}
{% set version = "0.2" %}
{% set sha256 = "231f5f80619e273d8e678fcb85fc57aab5161b61f1f8ab239a6fc475f509fd05" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - orca
    - pandana
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - urbansim_defaults

about:
  home: https://github.com/udst/urbansim_defaults
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Starter models and functionality to use with UrbanSim'
  doc_url: https://udst.github.io/urbansim_defaults/
  dev_url: https://github.com/udst/urbansim_defaults

extra:
  recipe-maintainers:
    - smmaurer
